name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          default: true
          profile: minimal
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
